language: php

services:
    - docker

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

addons:
    apt:
        packages:
            - pandoc

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    allow_failures:
        - php: nightly

before_script:
    - composer install --no-interaction

script:
    - ./vendor/bin/phpunit

jobs:
    include:
        - stage: php-cs-fixer
          php: 7.4
          script:
              - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
              - php php-cs-fixer fix --dry-run --diff --using-cache=no -vvv
        - stage: phpstan
          php: 7.4
          script:
              - docker pull phpstan/phpstan
              - docker run --rm -v $TRAVIS_BUILD_DIR:/app phpstan/phpstan analyse --level 5 --no-interaction --no-progress /app/src
        - stage: coverage
          php: 7.4
          script:
              - ./vendor/bin/phpunit --coverage-clover=coverage.xml
              - bash <(curl -s https://codecov.io/bash)

stages:
    - php-cs-fixer
    - phpstan
    - test
    - coverage
